var config = {
    texts: [
        "08/12/2020...",
        "Dương thân mến",     
        "Hôm nay là sinh nhật cậu", 
        "Linh chúc Dương tuổi mới",
        "Sức khoẻ dồi dào",
        "Gia đình luôn luôn sung túc",
        "Thật nhiều may mắn",
        "Ngày càng xinh đẹp",
        "Sinh nhật vui vẻ ý nghĩa nha nhá",
        "-Linh-",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Love you <3"
    ],
    imgs: {
        "08/12/2020...": "./imgs/duong.jpg",
        "Dương thân mến": "./imgs/duong1.jpg",
        "Hôm nay là sinh nhật cậu":"./imgs/duong2.jpg",  
        "Linh chúc Dương tuổi mới":"./imgs/duong3.jpg",
        "Sức khoẻ dồi dào":"./imgs/duong4.jpg",
        "Gia đình luôn luôn sung túc":"./imgs/duong5.jpg",
        "Thật nhiều may mắn":"./imgs/duong6.jpg",
        "Ngày càng xinh đẹp": "./imgs/duong7.jpg",
        "Sinh nhật vui vẻ ý nghĩa nha nhá":"./imgs/duong8.jpg",
        "-Linh-":"./imgs/linh.jpg",

    },
    desc: {
        turn_on: "Bấm vào đây đi Dương",
        play: "Thêm nhạc cho sôi động",
        bannar_coming: "Trang trí sinh nhật nào!",
        balloons_flying: "Thêm bóng bay",
        cake_fadein: "Thêm bánh gato nữa",
        light_candle: "Châm nến",
        wish_message: "Chúc mừng sinh nhật Dương!",
        story: "Đôi lời nhắn nhủ",
    }
};
